### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by cynicXer** [ivanfratric/winafl#10]
Admittedly, I'm a noob at building software on Windoze with cMake so this may be PEBCAK.  When I followed the README instructions for compiling WinAFL, I got the following linker errors.  I was trying to build for 32 bit arch using the VS x86 Native Tools Command Prompt.  VS 14.0 on Windows 10.  Am I missing something?

Thanks!

```
Project "C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\ALL_BUILD.vcxproj" (1) is building "C:\User
s\cynicxer\Desktop\winafl-master\winafl-master\build32\test_gdiplus.vcxproj" (5) on node 1 (default targets).
PrepareForBuild:
  Creating directory "test_gdiplus.dir\Release\".
  Creating directory "test_gdiplus.dir\Release\test_gdiplus.tlog\".
InitializeBuildStatus:
  Creating "test_gdiplus.dir\Release\test_gdiplus.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Building Custom Rule C:/Users/cynicxer/Desktop/winafl-master/winafl-master/CMakeLists.txt
  CMake does not need to re-run because C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\CMakeFiles\g
  enerate.stamp is up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /I"C:\Users\cynicxer\Desktop\DynamoRIO-Wind
  ows-6.2.0-2\cmake\..\include" /I"C:\Users\cynicxer\Desktop\DynamoRIO-Windows-6.2.0-2\cmake\..\ext\include" /nolo
  go /W1 /WX- /O2 /Oy- /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Z
  c:inline /Fo"test_gdiplus.dir\Release\\" /Fd"test_gdiplus.dir\Release\vc140.pdb" /Gd /TP /analyze- /errorReport:
  queue "C:\Users\cynicxer\Desktop\winafl-master\winafl-master\gdiplus.cpp"
  gdiplus.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\cynicxer\D
  esktop\winafl-master\winafl-master\build32\Release\test_gdiplus.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32
  .lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib gdiplus.lib /M
  ANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/Users/cynicxer/Desktop/winafl
  -master/winafl-master/build32/Release/test_gdiplus.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPL
  IB:"C:/Users/cynicxer/Desktop/winafl-master/winafl-master/build32/Release/test_gdiplus.lib" /MACHINE:X86 /SAFESE
  H  /machine:X86 test_gdiplus.dir\Release\gdiplus.obj
  test_gdiplus.vcxproj -> C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\Release\test_gdiplus.exe
FinalizeBuildStatus:
  Deleting file "test_gdiplus.dir\Release\test_gdiplus.tlog\unsuccessfulbuild".
  Touching "test_gdiplus.dir\Release\test_gdiplus.tlog\test_gdiplus.lastbuildstate".
Done Building Project "C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\test_gdiplus.vcxproj" (defaul
t targets).

Project "C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\ALL_BUILD.vcxproj" (1) is building "C:\User
s\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj" (6) on node 1 (default targets).
PrepareForBuild:
  Creating directory "winafl.dir\Release\".
  Creating directory "winafl.dir\Release\winafl.tlog\".
InitializeBuildStatus:
  Creating "winafl.dir\Release\winafl.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Building Custom Rule C:/Users/cynicxer/Desktop/winafl-master/winafl-master/CMakeLists.txt
  CMake does not need to re-run because C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\CMakeFiles\g
  enerate.stamp is up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /I"C:\Users\cynicxer\Desktop\DynamoRIO-Wind
  ows-6.2.0-2\cmake\..\include" /I"C:\Users\cynicxer\Desktop\DynamoRIO-Windows-6.2.0-2\cmake\..\ext\include" /Zi /
  nologo /W3 /WX- /O2 /Ob1 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D X86_32 /D WINDOWS /D "CMAKE_INTDIR=\"Release\""
  /D winafl_EXPORTS /D _WINDLL /D _MBCS /Gm- /MT /GS- /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"winafl.d
  ir\Release\\" /Fd"winafl.dir\Release\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Users\cynicxer\Desktop\
  winafl-master\winafl-master\winafl.c" "C:\Users\cynicxer\Desktop\winafl-master\winafl-master\modules.c"
  winafl.c
  modules.c
  Generating Code...
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\cynicxer\D
  esktop\winafl-master\winafl-master\build32\Release\winafl.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib g
  di32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib libcmt.lib "C:\Users
  \cynicxer\Desktop\DynamoRIO-Windows-6.2.0-2\ext\lib32\release\drx.lib" "C:\Users\cynicxer\Desktop\DynamoRIO-Wind
  ows-6.2.0-2\ext\lib32\release\drcontainers.lib" "C:\Users\cynicxer\Desktop\DynamoRIO-Windows-6.2.0-2\ext\lib32\r
  elease\drreg.lib" "C:\Users\cynicxer\Desktop\DynamoRIO-Windows-6.2.0-2\ext\lib32\release\drwrap.lib" "C:\Users\c
  ynicxer\Desktop\DynamoRIO-Windows-6.2.0-2\lib32\ntdll_imports.lib" "C:\Users\cynicxer\Desktop\DynamoRIO-Windows-
  6.2.0-2\ext\lib32\release\drmgr.lib" "C:\Users\cynicxer\Desktop\DynamoRIO-Windows-6.2.0-2\ext\lib32\release\drco
  ntainers.lib" "C:\Users\cynicxer\Desktop\DynamoRIO-Windows-6.2.0-2\lib32\release\dynamorio.lib" /MANIFEST /MANIF
  ESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/Users/cynicxer/Desktop/winafl-master/winafl
  -master/build32/Release/winafl.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/cynicxe
  r/Desktop/winafl-master/winafl-master/build32/Release/winafl.lib" /MACHINE:X86 /SAFESEH  /machine:X86 /nodefault
  lib /DLL winafl.dir\Release\winafl.obj
  winafl.dir\Release\modules.obj
     Creating library C:/Users/cynicxer/Desktop/winafl-master/winafl-master/build32/Release/winafl.lib and object
  C:/Users/cynicxer/Desktop/winafl-master/winafl-master/build32/Release/winafl.exp
libcmt.lib(dll_dllmain.obj) : error LNK2019: unresolved external symbol __initterm referenced in function "int __c
decl dllmain_crt_process_attach(struct HINSTANCE__ * const,void * const)" (?dllmain_crt_process_attach@@YAHQAUHINS
TANCE__@@QAX@Z) [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(dll_dllmain.obj) : error LNK2019: unresolved external symbol __initterm_e referenced in function "int _
_cdecl dllmain_crt_process_attach(struct HINSTANCE__ * const,void * const)" (?dllmain_crt_process_attach@@YAHQAUHI
NSTANCE__@@QAX@Z) [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(dll_dllmain.obj) : error LNK2001: unresolved external symbol __except_handler4 [C:\Users\cynicxer\Deskt
op\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility.obj) : error LNK2001: unresolved external symbol __except_handler4 [C:\Users\cynicxer\Desktop\w
inafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(_sehprolg4_.obj) : error LNK2001: unresolved external symbol __except_handler4 [C:\Users\cynicxer\Deskt
op\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __seh_filter_dll referenced in function ___scr
t_dllmain_exception_filter [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __configure_narrow_argv referenced in function
 "public: static int __cdecl __scrt_narrow_argv_policy::configure_argv(void)" (?configure_argv@__scrt_narrow_argv_
policy@@SAHXZ) [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __initialize_narrow_environment referenced in
function ___scrt_dllmain_after_initialize_c [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.
vcxproj]
libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __initialize_onexit_table referenced in functi
on ___scrt_initialize_onexit_tables [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __register_onexit_function referenced in funct
ion __onexit [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __execute_onexit_table referenced in function
___scrt_dllmain_uninitialize_c [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __crt_atexit referenced in function __onexit [
C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __crt_at_quick_exit referenced in function _at
_quick_exit [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __cexit referenced in function ___scrt_dllmain
_uninitialize_c [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(tncleanup.obj) : error LNK2019: unresolved external symbol ___std_type_info_destroy_list referenced in
function "void __cdecl __scrt_uninitialize_type_info(void)" (?__scrt_uninitialize_type_info@@YAXXZ) [C:\Users\cyni
cxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
libcmt.lib(utility_desktop.obj) : error LNK2019: unresolved external symbol _terminate referenced in function ___s
crt_unhandled_exception_filter@4 [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\Release\winafl.dll : fatal error LNK1120: 14 unresol
ved externals [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
Done Building Project "C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj" (default targ
ets) -- FAILED.

Done Building Project "C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\ALL_BUILD.vcxproj" (default t
argets) -- FAILED.


Build FAILED.

"C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj" (default target) (6) ->
(Link target) ->
  libcmt.lib(dll_dllmain.obj) : error LNK2019: unresolved external symbol __initterm referenced in function "int _
_cdecl dllmain_crt_process_attach(struct HINSTANCE__ * const,void * const)" (?dllmain_crt_process_attach@@YAHQAUHI
NSTANCE__@@QAX@Z) [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(dll_dllmain.obj) : error LNK2019: unresolved external symbol __initterm_e referenced in function "int
 __cdecl dllmain_crt_process_attach(struct HINSTANCE__ * const,void * const)" (?dllmain_crt_process_attach@@YAHQAU
HINSTANCE__@@QAX@Z) [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(dll_dllmain.obj) : error LNK2001: unresolved external symbol __except_handler4 [C:\Users\cynicxer\Des
ktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2001: unresolved external symbol __except_handler4 [C:\Users\cynicxer\Desktop
\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(_sehprolg4_.obj) : error LNK2001: unresolved external symbol __except_handler4 [C:\Users\cynicxer\Des
ktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __seh_filter_dll referenced in function ___s
crt_dllmain_exception_filter [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __configure_narrow_argv referenced in functi
on "public: static int __cdecl __scrt_narrow_argv_policy::configure_argv(void)" (?configure_argv@__scrt_narrow_arg
v_policy@@SAHXZ) [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __initialize_narrow_environment referenced i
n function ___scrt_dllmain_after_initialize_c [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winaf
l.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __initialize_onexit_table referenced in func
tion ___scrt_initialize_onexit_tables [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxpro
j]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __register_onexit_function referenced in fun
ction __onexit [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __execute_onexit_table referenced in functio
n ___scrt_dllmain_uninitialize_c [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __crt_atexit referenced in function __onexit
 [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __crt_at_quick_exit referenced in function _
at_quick_exit [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __cexit referenced in function ___scrt_dllma
in_uninitialize_c [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(tncleanup.obj) : error LNK2019: unresolved external symbol ___std_type_info_destroy_list referenced i
n function "void __cdecl __scrt_uninitialize_type_info(void)" (?__scrt_uninitialize_type_info@@YAXXZ) [C:\Users\cy
nicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility_desktop.obj) : error LNK2019: unresolved external symbol _terminate referenced in function __
_scrt_unhandled_exception_filter@4 [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]
  C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\Release\winafl.dll : fatal error LNK1120: 14 unres
olved externals [C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32\winafl.vcxproj]

    0 Warning(s)
    17 Error(s)

Time Elapsed 00:00:08.00

C:\Users\cynicxer\Desktop\winafl-master\winafl-master\build32>
```

**Comment by ivanfratric** [comment]
You might need to compile DynamoRIO from source yourself first. I think there were some changes in VS 2015 compared to the previous versions that might be causing this problem. This might be a related issue to https://github.com/DynamoRIO/dynamorio/issues/1902

The WinAFL binaries provided in the repo were built with VS 10.

**Comment by 0vercl0k** [comment]
@cynicXer check https://github.com/DynamoRIO/dynamorio/pull/2125 and https://github.com/DynamoRIO/dynamorio/issues/1902 - this should be fixed if you use the trunk version :).

Cheers

**Comment by b1ack0wl** [comment]
I'm experiencing the same problems with Windows 10 x86. I've double checked the cmake files and have installed the VC runtime libraries multiple times.

The error is around resolving c functions like _snprintf. I've followed all of the 'fixes' but the error is still there. 

Environment: Windows 10 x86 - Visual Studio 15 Community.

**Comment by 0vercl0k** [comment]
Can you paste some of the errors you have? Which SDK are you using?

Cheers

2017-01-31 13:05 GMT-08:00 b1ack0wl <notifications@github.com>:

**Comment by b1ack0wl** [comment]
Hey! I'll run the build again in a moment. I just need to boot up my Virtual Machine.
I suspect that VS2015 is the culprit since I had problems building dynamorio and opened a case with them: https://github.com/DynamoRIO/dynamorio/issues/2166

As far as the SDK I'm using the following:
 - Windows 10 SDK
 - .NET SDK (Included in the WinDBG SDK setup)

If I'm able to fix the issue then I'll submit a pull req :)

**Comment by 0vercl0k** [comment]
Try to link against 'legacy_stdio_definitions.lib' :-) pretty sure that's
the problem here!

Cheers

2017-02-02 10:25 GMT-08:00 b1ack0wl <notifications@github.com>:

**Comment by b1ack0wl** [comment]
Cool! I'll give this a shot in a few hours. :)

**Comment by 0vercl0k** [comment]
@b1ack0wl did it work :)?

Cheers

**Comment by b1ack0wl** [comment]
Hey! I might need some assistance with modifying the cmake files to include the stdio definitions. I took a small stab at it but still ended up with linking problems (same as before).

**Comment by 0vercl0k** [comment]
No worries :) - how about you add in the CMakeList file something like
"target_link_libraries(afl-fuzz libcmt libvcruntime libucrt)" and
re-generate the VS solution?
Let me know if it helps!

Cheers


2017-02-16 8:11 GMT-08:00 b1ack0wl <notifications@github.com>:

**Comment by b1ack0wl** [comment]
I added the statement but I'm still seeing the same issues. I'm using the pre-compiled version of DynamoRIO-6.2.0-2 to build WinAFL against since their CMakeFile is gonna take some time to take apart. 

```
Build FAILED.

"C:\Users\WinAFL\Desktop\winafl-master\build32\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj" (default target) (6) ->
(Link target) ->
  libcmt.lib(dll_dllmain.obj) : error LNK2019: unresolved external symbol __initterm referenced in function "int __cdec
l dllmain_crt_process_attach(struct HINSTANCE__ * const,void * const)" (?dllmain_crt_process_attach@@YAHQAUHINSTANCE__@
@QAX@Z) [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(dll_dllmain.obj) : error LNK2019: unresolved external symbol __initterm_e referenced in function "int __cd
ecl dllmain_crt_process_attach(struct HINSTANCE__ * const,void * const)" (?dllmain_crt_process_attach@@YAHQAUHINSTANCE_
_@@QAX@Z) [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(dll_dllmain.obj) : error LNK2001: unresolved external symbol __except_handler4 [C:\Users\WinAFL\Desktop\wi
nafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2001: unresolved external symbol __except_handler4 [C:\Users\WinAFL\Desktop\winafl
-master\build32\winafl.vcxproj]
  libcmt.lib(_sehprolg4_.obj) : error LNK2001: unresolved external symbol __except_handler4 [C:\Users\WinAFL\Desktop\wi
nafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __seh_filter_dll referenced in function ___scrt_d
llmain_exception_filter [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __configure_narrow_argv referenced in function "p
ublic: static int __cdecl __scrt_narrow_argv_policy::configure_argv(void)" (?configure_argv@__scrt_narrow_argv_policy@@
SAHXZ) [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __initialize_narrow_environment referenced in fun
ction ___scrt_dllmain_after_initialize_c [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __initialize_onexit_table referenced in function
___scrt_initialize_onexit_tables [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __register_onexit_function referenced in function
 __onexit [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __execute_onexit_table referenced in function ___
scrt_dllmain_uninitialize_c [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __crt_atexit referenced in function __onexit [C:\
Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __crt_at_quick_exit referenced in function _at_qu
ick_exit [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility.obj) : error LNK2019: unresolved external symbol __cexit referenced in function ___scrt_dllmain_un
initialize_c [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(tncleanup.obj) : error LNK2019: unresolved external symbol ___std_type_info_destroy_list referenced in fun
ction "void __cdecl __scrt_uninitialize_type_info(void)" (?__scrt_uninitialize_type_info@@YAXXZ) [C:\Users\WinAFL\Deskt
op\winafl-master\build32\winafl.vcxproj]
  libcmt.lib(utility_desktop.obj) : error LNK2019: unresolved external symbol _terminate referenced in function ___scrt
_unhandled_exception_filter@4 [C:\Users\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]
  C:\Users\WinAFL\Desktop\winafl-master\build32\Release\winafl.dll : fatal error LNK1120: 14 unresolved externals [C:\U
sers\WinAFL\Desktop\winafl-master\build32\winafl.vcxproj]

    0 Warning(s)
    17 Error(s)
```

I'll keep playing around with the CMakeLists file just in case I placed the statement in the wrong place. Thanks for helping me walk through this, I'm a big GNU guy so Windows has been my kryptonite for years :P

**Comment by b1ack0wl** [comment]
I got it! I added the following and now it builds with 0 issues

```
target_link_libraries(winafl "legacy_stdio_definitions.lib")
target_link_libraries(winafl "vcruntimed.lib")
target_link_libraries(winafl "ucrtd.lib")
target_link_libraries(winafl "msvcrt.lib")
```

I'm going to clean up the CMakeLists.txt file and then submit a pull request. :)

**Comment by 0vercl0k** [comment]
Awesome man!

Note that the vcruntimed/ucrtd/msvcrt are used for DLL debug builds (see
https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/)
so you should probably stick with "libcmt.lib   libvcruntime.lib
libucrt.lib".

Cheers

2017-02-17 8:55 GMT-08:00 b1ack0wl <notifications@github.com>:

**Comment by b1ack0wl** [comment]
Good catch! I didn't realize that I linked the Debug libraries. I'll submit a pull request later on today (~3-4 hours from now)

**Comment by ivanfratric** [comment]
Thanks for the fix! I'm closing this bug.
